version: '3.7'

services:

  electric:
    build:
      context: .
      dockerfile: Dockerfile
    image: electric:latest
    container_name: electric
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "250000k"
        max-file: "2"
    environment: 
      - TZ=America/Montreal
    ports: 
      - 51234:51234
    networks:
      - electric-net

networks:
    electric-net:
      name: electric-net
      driver: bridge
